# Generated by Django 3.2.9 on 2022-04-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=60)),
                ('Department', models.CharField(max_length=60)),
                ('Category', models.CharField(max_length=60)),
                ('SubCategory', models.CharField(max_length=60)),
            ],
        ),
    ]
